Repository GSG-G7/far-nearer-v2, pull requests merged in 2019-11, with the labels that each got.

#5 Cloudinary
  client/src/components/pages/ViewBuildings/Map.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/emptyBuildings/post.js
  server/uploads/building.png
  server/utils/upload.js
Labels: Awaiting Review

#4 context and building page
  client/src/components/app/index.js
  client/src/components/app/style.css
  client/src/components/pages/Building/building.module.css
  client/src/components/pages/Building/index.js
  client/src/components/pages/Error/error.module.css
  client/src/components/pages/Error/index.js
  client/src/components/pages/ViewBuildings/Map.js
  client/src/components/pages/ViewBuildings/Table.js
  client/src/components/pages/ViewBuildings/index.js
  client/src/components/pages/ViewBuildings/view.module.css
  client/src/components/utils/Footer/index.js
  client/src/contexts/buildingContext.js
  package-lock.json
Labels: Awaiting Review

#11 Minor changes to wording and spelling
  client/public/index.html
  client/src/components/app/index.js
  client/src/components/pages/AboutUs/index.js
  client/src/components/pages/Home/Header/index.js
  client/src/components/pages/Home/ReportBuilding/Form/FirstStep.js
  client/src/components/pages/Home/ReportBuilding/Form/SecondStep.js
  client/src/components/pages/Home/ReportBuilding/Form/ThirdStep.js
  client/src/components/pages/Home/ReportBuilding/Form/index.js
  client/src/components/pages/Home/ReportBuilding/index.js
  client/src/components/pages/ViewBuildings/Map.js
  client/src/components/utils/Footer/Subscribe.js
  client/src/components/utils/Footer/footer.module.css
  client/src/components/utils/Footer/index.js
Labels: Awaiting Review

#16 cron jobs change time for emails
  server/controllers/mailList/sendUpdateEmails.js
Labels: Awaiting Review

#15 sign in
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/mailList/sendEmail.js
  server/controllers/mailList/sendUpdateEmails.js
  server/controllers/middleware/auth/index.js
  server/controllers/middleware/errorHandle.js
  server/controllers/middleware/index.js
  server/controllers/users/index.js
  server/controllers/users/signIn.js
  server/models/config/index.js
  server/models/queries/index.js
  server/models/queries/users.js
  server/validation/index.js
  server/validation/userSchema.js
Labels: Awaiting Review, Back-End

#23 logout controller
  server/controllers/index.js
  server/controllers/users/index.js
  server/controllers/users/logout.js
Labels: Awaiting Review

#14 Sign up
  server/controllers/index.js
  server/controllers/users/index.js
  server/controllers/users/signIn.js
  server/controllers/users/singUp.js
  server/models/queries/index.js
  server/models/queries/users.js
  server/validation/index.js
  server/validation/userSchema.js
Labels: Awaiting Review, Back-End

#25 add isAuth route
  server/controllers/index.js
Labels: Awaiting Review

#19 sign in page Front-End
  client/src/components/app/index.js
  client/src/components/app/style.css
  client/src/components/pages/Building/index.js
  client/src/components/pages/SignIn/index.js
  client/src/components/pages/SignIn/signIn.module.css
  client/src/components/pages/ViewBuildings/Map.js
  client/src/components/pages/ViewBuildings/Table.js
  client/src/components/pages/ViewBuildings/index.js
  server/controllers/emptyBuildings/getBuilding.js
  server/controllers/emptyBuildings/index.js
  server/controllers/index.js
  server/controllers/users/signIn.js
  server/models/queries/emptyBuildings.js
  server/models/queries/index.js
Labels: Front-End

#20 Sign-up page
  client/src/components/app/index.js
  client/src/components/app/style.css
  client/src/components/pages/SignUp/index.js
  client/src/components/pages/SignUp/signUp.module.css
  server/validation/userSchema.js
Labels: Awaiting Review, Front-End

#26 login button
  client/src/components/app/index.js
  client/src/components/pages/SignIn/index.js
  client/src/components/pages/SignUp/index.js
  client/src/components/utils/Navbar/index.js
  client/src/components/utils/Navbar/navbar.module.css
Labels: Awaiting Review
